# Generated by Django 5.1.7 on 2025-04-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_tracker', '0002_transaction_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='notes',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
