# Generated by Django 5.1.5 on 2025-02-02 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_tracker', '0003_alter_transaction_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='decsription',
            new_name='description',
        ),
    ]
