# Generated by Django 5.1.5 on 2025-02-26 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_tracker', '0004_rename_decsription_transaction_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
